version: "3"
services:
  db:
    container_name: postgres_db
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped

